services:
  - type: web
    name: telegram-bot
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: python jilibot.py
    plan: free
    autoDeploy: true
